# CodeRabbit 설정 파일

language: ko

reviews:
  auto_review:
    enabled: true    # 자동 리뷰 활성화
    drafts: true     # Draft PR도 리뷰
  level: comprehensive  # 포괄적 리뷰
  path_filters:          # 파일 패턴 제외 없음
    - "!**/*.md"
    - "!**/package-lock.json"
    - "!**/yarn.lock"
  focus:
    - correctness
    - performance
    - security
    - maintainability
    - best_practices

chat:
  enabled: true
  auto_reply: false

summaries:
  enabled: true
  release_notes: true

poem:
  enabled: false

labels:
  enabled: true

reviewers:
  auto_request: true   # 자동으로 리뷰어 요청

custom_prompts:
  - name: "보안 체크"
    prompt: "보안 취약점이 있는지 특히 주의깊게 검토해주세요"
  - name: "성능 체크"
    prompt: "성능 이슈가 있는지 확인해주세요"

knowledge_base:
  - "TypeScript와 React 모범 사례를 따르세요"
  - "테스트 코드 작성을 권장합니다"
  - "명확한 변수명과 함수명을 사용하세요"
