-- 초기 데이터베이스 설정
CREATE DATABASE IF NOT EXISTS heboard CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE heboard;

-- 예시: 초기 테이블 생성 (필요시 수정)
-- CREATE TABLE IF NOT EXISTS users (
--     id BIGINT AUTO_INCREMENT PRIMARY KEY,
--     username VARCHAR(50) NOT NULL UNIQUE,
--     email VARCHAR(100) NOT NULL UNIQUE,
--     password VARCHAR(255) NOT NULL,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
-- );