name: "기능 추가"
description: "새로운 기능 제안"
title: "[FEAT] "
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: 기능 설명
      description: 어떤 기능을 추가하고 싶으신가요?
      placeholder: 기능에 대해 설명해주세요
    validations:
      required: true
  - type: textarea
    attributes:
      label: 해야 할 일
      description: 구현을 위해 필요한 작업들
      placeholder: |
        - [ ] API 구현
        - [ ] 테스트 코드 작성
    validations:
      required: false
  - type: textarea
    attributes:
      label: 추가 설명
      description: 더 하고 싶은 말이 있다면 작성해주세요
    validations:
      required: false